export const SHOW_UPLOADER = 'SHOW_UPLOADER';
export const HIDE_UPLOADER = 'HIDE_UPLOADER';
export const ADD_UPLOAD_FILE = 'ADD_UPLOAD_FILE';
export const CHANGE_UPLOAD_FILE = 'CHANGE_UPLOAD_FILE';
export const REMOVE_UPLOAD_FILE = 'REMOVE_UPLOAD_FILE';
